-- ============================================================================
-- CHAT SYSTEM SCHEMA
-- Version: V4
-- Purpose: Enterprise-grade chat management with context preferences
-- Design Patterns: Enums as tables, soft deletes, audit trails
-- ============================================================================

-- ============================================================================
-- 1. ENUM TABLES (Better than CHECK constraints for maintainability)
-- ============================================================================

/**
 * Conversation Status Enum
 * Allows easy querying, filtering, and future status additions
 * No need to modify table structure when adding new statuses
 */
CREATE TABLE IF NOT EXISTS conversation_status (
    status_id SMALLINT PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO conversation_status (status_id, status_name, description) VALUES
    (1, 'ACTIVE', 'Conversation is currently active'),
    (2, 'ARCHIVED', 'Conversation archived by user'),
    (3, 'DELETED', 'Conversation soft-deleted'),
    (4, 'PAUSED', 'Conversation paused temporarily')
ON CONFLICT DO NOTHING;

/**
 * Message Role Enum
 * Defines who sent the message (user, assistant, system)
 */
CREATE TABLE IF NOT EXISTS message_role (
    role_id SMALLINT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO message_role (role_id, role_name, description) VALUES
    (1, 'USER', 'Message sent by user'),
    (2, 'ASSISTANT', 'Response generated by AI'),
    (3, 'SYSTEM', 'System message (e.g., errors, notifications)')
ON CONFLICT DO NOTHING;

/**
 * Context Level Enum
 * Determines how deeply user profile is referenced
 */
CREATE TABLE IF NOT EXISTS context_level (
    level_id SMALLINT PRIMARY KEY,
    level_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO context_level (level_id, level_name, description) VALUES
    (1, 'MINIMAL', 'No user data references'),
    (2, 'BALANCED', 'Mention goals/skills when relevant'),
    (3, 'DEEP', 'Actively reference profile, proactively suggest')
ON CONFLICT DO NOTHING;

/**
 * Response Style Enum
 * Controls verbosity and depth of AI responses
 */
CREATE TABLE IF NOT EXISTS response_style (
    style_id SMALLINT PRIMARY KEY,
    style_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    max_tokens INT DEFAULT 1000,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO response_style (style_id, style_name, description, max_tokens) VALUES
    (1, 'CONCISE', 'Short, direct answers (2-3 paragraphs)', 500),
    (2, 'BALANCED', 'Medium-length, comprehensive (5-7 paragraphs)', 1000),
    (3, 'DETAILED', 'Comprehensive, all angles covered', 1500)
ON CONFLICT DO NOTHING;

/**
 * Tone Enum
 * Controls the personality and formality of responses
 */
CREATE TABLE IF NOT EXISTS ai_tone (
    tone_id SMALLINT PRIMARY KEY,
    tone_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    system_prompt_modifier TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ai_tone (tone_id, tone_name, description, system_prompt_modifier) VALUES
    (1, 'PROFESSIONAL', 'Formal, direct, business-like', 'Keep responses professional and concise'),
    (2, 'CASUAL', 'Friendly, conversational, approachable', 'Be friendly and conversational, use casual language'),
    (3, 'MENTORING', 'Encouraging, explanatory, supportive', 'Be a supportive mentor, encourage learning')
ON CONFLICT DO NOTHING;

/**
 * Plan Type Enum
 * Defines user subscription tier
 */
CREATE TABLE IF NOT EXISTS plan_type (
    plan_id SMALLINT PRIMARY KEY,
    plan_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    max_conversations INT NOT NULL,
    max_messages_per_month INT,
    features JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO plan_type (plan_id, plan_name, description, max_conversations, max_messages_per_month, features) VALUES
    (1, 'FREE', 'Free tier with limited chats', 2, 100, '{"include_resources": true, "basic_preferences": true}'::jsonb),
    (2, 'PREMIUM', 'Premium with unlimited chats', 10, 1000, '{"all_features": true, "priority_api": false}'::jsonb),
    (3, 'PRO', 'Professional tier with all features', 999, 999999, '{"all_features": true, "priority_api": true, "analytics": true}'::jsonb)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- 2. CORE CHAT TABLES
-- ============================================================================

/**
 * Chat Conversations Table
 * Stores metadata about conversations
 * Design: Minimal data, references to other tables for details
 */
CREATE TABLE IF NOT EXISTS chat_conversations (
    conversation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,

    -- Conversation metadata
    title VARCHAR(255),
    description TEXT,

    -- Status tracking
    status_id SMALLINT NOT NULL DEFAULT 1,

    -- Message tracking
    message_count INT DEFAULT 0,
    last_message_id UUID,
    last_message_at TIMESTAMP,

    -- Summary for AI context (refreshed periodically)
    conversation_summary TEXT,
    summary_last_updated TIMESTAMP,

    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,  -- Soft delete support

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (status_id) REFERENCES conversation_status(status_id),
    CONSTRAINT valid_summary_timestamp CHECK (summary_last_updated IS NULL OR summary_last_updated <= CURRENT_TIMESTAMP)
);

-- Indexes for optimal query performance
CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_id
    ON chat_conversations(user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_created
    ON chat_conversations(user_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_chat_conversations_status
    ON chat_conversations(status_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_chat_conversations_last_message
    ON chat_conversations(last_message_at DESC)
    WHERE deleted_at IS NULL;

/**
 * Chat Messages Table (Hot Data - Recent messages only)
 * Stores recent messages for quick retrieval
 * Older messages are archived to MongoDB
 *
 * Strategy: Keep only last 50 messages per conversation in PostgreSQL
 * for performance, archive rest to MongoDB
 */
CREATE TABLE IF NOT EXISTS chat_messages (
    message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL,
    user_id UUID NOT NULL,

    -- Message content & metadata
    role_id SMALLINT NOT NULL,
    content TEXT NOT NULL,

    -- Token count for API cost estimation
    token_count INT,

    -- Message metadata
    is_cached BOOLEAN DEFAULT false,  -- True if response came from cache
    gemini_finish_reason VARCHAR(50),  -- Why Gemini stopped (STOP, SAFETY, etc)

    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,  -- Soft delete support

    -- Constraints
    FOREIGN KEY (conversation_id) REFERENCES chat_conversations(conversation_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES message_role(role_id),
    CONSTRAINT valid_token_count CHECK (token_count IS NULL OR token_count > 0),
    CONSTRAINT non_empty_content CHECK (LENGTH(TRIM(content)) > 0)
);

-- Indexes for optimal query performance
CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation_created
    ON chat_messages(conversation_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_created
    ON chat_messages(user_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_chat_messages_role
    ON chat_messages(role_id)
    WHERE deleted_at IS NULL;

-- Partial index for cached messages (quick lookup)
CREATE INDEX IF NOT EXISTS idx_chat_messages_cached
    ON chat_messages(conversation_id, is_cached)
    WHERE is_cached = true AND deleted_at IS NULL;

-- ============================================================================
-- 3. USER PREFERENCES TABLE
-- ============================================================================

/**
 * User AI Preferences Table
 * Stores how each user wants AI to respond
 * Uses foreign keys to enum tables for maintainability
 */
CREATE TABLE IF NOT EXISTS user_ai_preferences (
    preference_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE,

    -- Context & Content Preferences
    context_level_id SMALLINT NOT NULL DEFAULT 2,  -- BALANCED
    response_style_id SMALLINT NOT NULL DEFAULT 2,  -- BALANCED
    tone_id SMALLINT NOT NULL DEFAULT 3,  -- MENTORING

    -- Feature Toggles
    include_resources BOOLEAN NOT NULL DEFAULT true,
    include_examples BOOLEAN NOT NULL DEFAULT true,
    include_timeline BOOLEAN NOT NULL DEFAULT true,
    include_user_context BOOLEAN NOT NULL DEFAULT true,

    -- UI Preferences
    show_customize_button BOOLEAN NOT NULL DEFAULT true,
    show_tips_on_first_messages BOOLEAN NOT NULL DEFAULT true,
    auto_summarize_conversations BOOLEAN NOT NULL DEFAULT true,

    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (context_level_id) REFERENCES context_level(level_id),
    FOREIGN KEY (response_style_id) REFERENCES response_style(style_id),
    FOREIGN KEY (tone_id) REFERENCES ai_tone(tone_id)
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_ai_preferences_user_id
    ON user_ai_preferences(user_id);

-- ============================================================================
-- 4. CHAT SESSION & FREE TIER LIMIT TABLE
-- ============================================================================

/**
 * Chat Sessions Table
 * Tracks user subscription info and conversation limits
 * One session per user, updated when plan changes
 */
CREATE TABLE IF NOT EXISTS chat_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE,

    -- Plan information
    plan_id SMALLINT NOT NULL DEFAULT 1,  -- FREE
    active_conversations_count INT DEFAULT 0,

    -- Limits (denormalized from plan_type table for performance)
    max_conversations_allowed INT NOT NULL DEFAULT 2,
    messages_used_this_month INT DEFAULT 0,
    max_messages_per_month INT DEFAULT 100,

    -- Timestamps
    plan_started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    plan_renews_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES plan_type(plan_id),
    CONSTRAINT valid_conversation_count CHECK (active_conversations_count >= 0 AND active_conversations_count <= max_conversations_allowed),
    CONSTRAINT valid_message_count CHECK (messages_used_this_month >= 0 AND messages_used_this_month <= max_messages_per_month)
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_id
    ON chat_sessions(user_id);

CREATE INDEX IF NOT EXISTS idx_chat_sessions_plan_id
    ON chat_sessions(plan_id);

-- ============================================================================
-- 5. MESSAGE CACHE TABLE (Redis substitute for non-Redis setups)
-- ============================================================================

/**
 * AI Response Cache Table
 * Stores last response for fallback when Gemini is down
 * TTL managed by application or cleanup job
 */
CREATE TABLE IF NOT EXISTS ai_response_cache (
    cache_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    conversation_id UUID NOT NULL,

    -- Cached response
    request_hash VARCHAR(64) NOT NULL,  -- Hash of question for deduplication
    response_content TEXT NOT NULL,
    response_tokens INT,

    -- Metadata
    cached_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '24 hours'),
    hit_count INT DEFAULT 0,  -- How many times this cache was used

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (conversation_id) REFERENCES chat_conversations(conversation_id) ON DELETE CASCADE,
    CONSTRAINT valid_hash CHECK (LENGTH(request_hash) = 64)
);

-- Indexes for cache hits
CREATE INDEX IF NOT EXISTS idx_ai_response_cache_user_request
    ON ai_response_cache(user_id, request_hash)
    WHERE expires_at > CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_ai_response_cache_expires
    ON ai_response_cache(expires_at);

-- ============================================================================
-- 6. ENGAGEMENT & ANALYTICS TABLE
-- ============================================================================

/**
 * User Engagement Table
 * Tracks user interactions for analytics and nudges
 */
CREATE TABLE IF NOT EXISTS user_engagement (
    engagement_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,

    -- Counters
    total_conversations_created INT DEFAULT 0,
    total_messages_sent INT DEFAULT 0,
    total_preferences_changed INT DEFAULT 0,

    -- Temporal data
    first_chat_at TIMESTAMP,
    last_chat_at TIMESTAMP,
    last_preference_update_at TIMESTAMP,

    -- Flags for engagement strategies
    should_receive_nudge BOOLEAN DEFAULT true,
    last_nudge_sent_at TIMESTAMP,
    is_power_user BOOLEAN DEFAULT false,  -- 5+ conversations

    -- Audit
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_engagement_user_id
    ON user_engagement(user_id);

CREATE INDEX IF NOT EXISTS idx_user_engagement_last_chat
    ON user_engagement(last_chat_at DESC);

-- ============================================================================
-- 7. VIEWS FOR COMMON QUERIES (Performance optimization)
-- ============================================================================

/**
 * View: Active Conversations Per User
 * Used frequently, so create a view to simplify queries
 */
CREATE OR REPLACE VIEW v_active_conversations AS
SELECT
    cc.conversation_id,
    cc.user_id,
    cc.title,
    cc.message_count,
    cc.last_message_at,
    cs.status_name,
    COUNT(DISTINCT cm.message_id) AS actual_message_count
FROM chat_conversations cc
LEFT JOIN conversation_status cs ON cc.status_id = cs.status_id
LEFT JOIN chat_messages cm ON cc.conversation_id = cm.conversation_id AND cm.deleted_at IS NULL
WHERE cc.deleted_at IS NULL AND cs.status_name = 'ACTIVE'
GROUP BY cc.conversation_id, cc.user_id, cc.title, cc.message_count, cc.last_message_at, cs.status_name;

/**
 * View: User Context for AI (all info needed for Gemini)
 */
CREATE OR REPLACE VIEW v_user_ai_context AS
SELECT
    u.user_id,
    u.name,
    u.current_role,
    u.target_role,
    u.skills,
    u.experience_level,
    uap.context_level_id,
    cl.level_name AS context_level,
    uap.response_style_id,
    rs.style_name AS response_style,
    rs.max_tokens,
    uap.tone_id,
    at.tone_name AS tone,
    at.system_prompt_modifier,
    uap.include_resources,
    uap.include_examples,
    uap.include_timeline,
    uap.include_user_context
FROM users u
LEFT JOIN user_ai_preferences uap ON u.user_id = uap.user_id
LEFT JOIN context_level cl ON uap.context_level_id = cl.level_id
LEFT JOIN response_style rs ON uap.response_style_id = rs.style_id
LEFT JOIN ai_tone at ON uap.tone_id = at.tone_id;

-- ============================================================================
-- 8. FUNCTION FOR AUTO-UPDATE TIMESTAMPS
-- ============================================================================

/**
 * Function to automatically update updated_at timestamp
 * Prevents forgotten timestamp updates
 */
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for timestamp updates
CREATE TRIGGER trg_chat_conversations_update
BEFORE UPDATE ON chat_conversations
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_user_ai_preferences_update
BEFORE UPDATE ON user_ai_preferences
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_user_engagement_update
BEFORE UPDATE ON user_engagement
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_chat_sessions_update
BEFORE UPDATE ON chat_sessions
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();

-- ============================================================================
-- 9. FUNCTION TO CHECK CONVERSATION LIMIT
-- ============================================================================

/**
 * Function to check if user can create new conversation
 * Returns: true if allowed, false if limit reached
 * Called from application before creating new conversation
 */
CREATE OR REPLACE FUNCTION can_user_create_conversation(user_id_param UUID)
RETURNS BOOLEAN AS $$
DECLARE
    active_count INT;
    max_allowed INT;
BEGIN
    SELECT
        active_conversations_count,
        max_conversations_allowed
    INTO active_count, max_allowed
    FROM chat_sessions
    WHERE user_id = user_id_param;

    RETURN COALESCE(active_count, 0) < COALESCE(max_allowed, 2);
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 10. COMMENT DOCUMENTATION (Self-documenting database)
-- ============================================================================

COMMENT ON TABLE chat_conversations IS 'Stores conversation metadata and status. Design: Minimal data per row for performance.';
COMMENT ON COLUMN chat_conversations.conversation_summary IS 'AI-generated summary refreshed every 20 messages to prevent token bloat in Gemini context.';
COMMENT ON COLUMN chat_conversations.deleted_at IS 'Soft delete timestamp - allows data recovery and audit trails.';

COMMENT ON TABLE chat_messages IS 'Stores recent messages only. Older messages archived to MongoDB. Strategy: Keep hot data in PostgreSQL for speed.';
COMMENT ON COLUMN chat_messages.is_cached IS 'True if this response came from cache (fallback when Gemini down). Helps identify API issues.';

COMMENT ON TABLE user_ai_preferences IS 'User customization of AI responses. Uses enum tables for maintainability - no need to alter schema for new options.';

COMMENT ON FUNCTION can_user_create_conversation(UUID) IS 'Check if user has reached conversation limit based on plan. Called before conversation creation.';

-- ============================================================================
-- END OF MIGRATION V4
-- ============================================================================
