package com.skillsync.enums;

/**
 * Message Role Enum
 * Determines who sent the message (user, AI assistant, or system)
 *
 * @author SkillSync Team
 * @version 1.0
 */
public enum MessageRole {
    /**
     * Message sent by the user
     */
    USER("USER", "Message sent by user", (short) 1),

    /**
     * Response generated by AI assistant (Gemini)
     */
    ASSISTANT("ASSISTANT", "Response generated by AI", (short) 2),

    /**
     * System message (errors, notifications, etc)
     */
    SYSTEM("SYSTEM", "System message (errors, notifications)", (short) 3);

    private final String roleName;
    private final String description;
    private final short databaseId;

    MessageRole(String roleName, String description, short databaseId) {
        this.roleName = roleName;
        this.description = description;
        this.databaseId = databaseId;
    }

    public short getDatabaseId() {
        return databaseId;
    }

    public String getRoleName() {
        return roleName;
    }

    public String getDescription() {
        return description;
    }

    public static MessageRole fromDatabaseId(short id) {
        for (MessageRole role : MessageRole.values()) {
            if (role.databaseId == id) {
                return role;
            }
        }
        throw new IllegalArgumentException("Unknown message role ID: " + id);
    }

    public static MessageRole fromString(String roleName) {
        try {
            return MessageRole.valueOf(roleName.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Unknown message role: " + roleName, e);
        }
    }
}
